name: classmate_app
description: AI-Powered Tuition Finder for Sri Lanka
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  cupertino_icons: ^1.0.6
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  cloud_functions: ^6.0.1
  firebase_messaging: ^16.0.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets: (no area CSV needed)
