// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WZXqGSDJ-Q2vE9gvm9Z8pZp4KfpS3g8',
    appId: '1:871613294867:web:a81b23b2e8b14f5f6ed2e6',
    messagingSenderId: '871613294867',
    projectId: 'ai-classmate-dev',
    authDomain: 'ai-classmate-dev.firebaseapp.com',
    storageBucket: 'ai-classmate-dev.firebasestorage.app',
    measurementId: 'G-DWJQ9NW7YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlvekWA6ijai3RUO1OjlqaA6Omq4YI1A',
    appId: '1:871613294867:android:d60dad8665d47c816ed2e6',
    messagingSenderId: '871613294867',
    projectId: 'ai-classmate-dev',
    storageBucket: 'ai-classmate-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDCSqqKELTV9fDw5X99KDrlxWgQhpUHvo',
    appId: '1:871613294867:ios:b6cf4ac2b84aa8636ed2e6',
    messagingSenderId: '871613294867',
    projectId: 'ai-classmate-dev',
    storageBucket: 'ai-classmate-dev.firebasestorage.app',
    iosBundleId: 'com.example.classmateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7WZXqGSDJ-Q2vE9gvm9Z8pZp4KfpS3g8',
    appId: '1:871613294867:web:8ef7b7ef7e474ecc6ed2e6',
    messagingSenderId: '871613294867',
    projectId: 'ai-classmate-dev',
    authDomain: 'ai-classmate-dev.firebaseapp.com',
    storageBucket: 'ai-classmate-dev.firebasestorage.app',
    measurementId: 'G-77GCCQ4BYM',
  );
}
